import { parseOutputFormat, parseOutputDestination, parseBooleanFlag, loadOutputConfig } from '../outputConfig';

const mockGetInput = jest.fn();
const mockWarning = jest.fn();

jest.mock('@actions/core', () => ({
  getInput: (key: string) => mockGetInput(key),
  warning: (msg: string) => mockWarning(msg),
}));

function setupInputs(inputs: Record<string, string>) {
  mockGetInput.mockImplementation((key: string) => inputs[key] ?? '');
}

beforeEach(() => {
  jest.clearAllMocks();
});

describe('parseOutputFormat', () => {
  it('returns markdown for valid input', () => {
    expect(parseOutputFormat('markdown')).toBe('markdown');
  });

  it('returns json for valid input', () => {
    expect(parseOutputFormat('json')).toBe('json');
  });

  it('returns text for valid input', () => {
    expect(parseOutputFormat('TEXT')).toBe('text');
  });

  it('defaults to markdown for unknown format and warns', () => {
    expect(parseOutputFormat('xml')).toBe('markdown');
    expect(mockWarning).toHaveBeenCalledWith(expect.stringContaining('xml'));
  });
});

describe('parseOutputDestination', () => {
  it('returns slack', () => expect(parseOutputDestination('slack')).toBe('slack'));
  it('returns email', () => expect(parseOutputDestination('email')).toBe('email'));
  it('returns file', () => expect(parseOutputDestination('file')).toBe('file'));
  it('returns stdout', () => expect(parseOutputDestination('stdout')).toBe('stdout'));

  it('defaults to stdout for unknown destination and warns', () => {
    expect(parseOutputDestination('webhook')).toBe('stdout');
    expect(mockWarning).toHaveBeenCalledWith(expect.stringContaining('webhook'));
  });
});

describe('parseBooleanFlag', () => {
  it('returns true when input is "true"', () => expect(parseBooleanFlag('true', false)).toBe(true));
  it('returns false when input is "false"', () => expect(parseBooleanFlag('false', true)).toBe(false));
  it('returns default when input is empty', () => expect(parseBooleanFlag('', true)).toBe(true));
});

describe('loadOutputConfig', () => {
  it('loads defaults when no inputs provided', () => {
    setupInputs({});
    const config = loadOutputConfig();
    expect(config.format).toBe('markdown');
    expect(config.destination).toBe('stdout');
    expect(config.includeHeader).toBe(true);
    expect(config.includeFooter).toBe(false);
    expect(config.filePath).toBeUndefined();
  });

  it('loads custom format and destination', () => {
    setupInputs({ output_format: 'json', output_destination: 'file', output_file_path: 'out/digest.json' });
    const config = loadOutputConfig();
    expect(config.format).toBe('json');
    expect(config.destination).toBe('file');
    expect(config.filePath).toBe('out/digest.json');
  });

  it('defaults file path to digest.md when destination is file but path is empty', () => {
    setupInputs({ output_destination: 'file' });
    const config = loadOutputConfig();
    expect(config.filePath).toBe('digest.md');
    expect(mockWarning).toHaveBeenCalled();
  });

  it('loads footer text', () => {
    setupInputs({ output_include_footer: 'true', output_footer_text: 'Generated by pr-digest' });
    const config = loadOutputConfig();
    expect(config.includeFooter).toBe(true);
    expect(config.footerText).toBe('Generated by pr-digest');
  });
});
