import { appendFooter, buildFooterLines, formatTimestamp } from '../appendFooter';
import { CustomFooterConfig } from '../../config/customFooterConfig';

const baseConfig: CustomFooterConfig = {
  enabled: true,
  footerText: '',
  includeTimestamp: false,
  timestampFormat: 'locale',
  includeRepoLink: false,
};

describe('formatTimestamp', () => {
  const fixedDate = new Date('2024-03-15T12:00:00.000Z');

  it('returns ISO string for iso format', () => {
    expect(formatTimestamp(fixedDate, 'iso')).toBe('2024-03-15T12:00:00.000Z');
  });

  it('returns locale string for locale format', () => {
    const result = formatTimestamp(fixedDate, 'locale');
    expect(typeof result).toBe('string');
    expect(result.length).toBeGreaterThan(0);
  });

  it('returns relative string for relative format', () => {
    const recentDate = new Date(Date.now() - 5 * 60000);
    expect(formatTimestamp(recentDate, 'relative')).toBe('5 minutes ago');
  });

  it('handles singular minute', () => {
    const recentDate = new Date(Date.now() - 60000);
    expect(formatTimestamp(recentDate, 'relative')).toBe('1 minute ago');
  });

  it('handles hours in relative format', () => {
    const recentDate = new Date(Date.now() - 2 * 3600000);
    expect(formatTimestamp(recentDate, 'relative')).toBe('2 hours ago');
  });
});

describe('buildFooterLines', () => {
  it('returns empty array when nothing is configured', () => {
    const lines = buildFooterLines(baseConfig, {});
    expect(lines).toHaveLength(0);
  });

  it('includes custom footer text', () => {
    const config = { ...baseConfig, footerText: 'Auto-generated by pr-digest' };
    const lines = buildFooterLines(config, {});
    expect(lines).toContain('Auto-generated by pr-digest');
  });

  it('includes timestamp when enabled', () => {
    const config = { ...baseConfig, includeTimestamp: true, timestampFormat: 'iso' as const };
    const lines = buildFooterLines(config, { generatedAt: new Date('2024-01-01T00:00:00.000Z') });
    expect(lines.some((l) => l.includes('2024-01-01T00:00:00.000Z'))).toBe(true);
  });

  it('includes repo link when enabled and url provided', () => {
    const config = { ...baseConfig, includeRepoLink: true };
    const lines = buildFooterLines(config, { repoUrl: 'https://github.com/org/repo' });
    expect(lines.some((l) => l.includes('https://github.com/org/repo'))).toBe(true);
  });

  it('omits repo link when url is not provided', () => {
    const config = { ...baseConfig, includeRepoLink: true };
    const lines = buildFooterLines(config, {});
    expect(lines.some((l) => l.includes('View Repository'))).toBe(false);
  });
});

describe('appendFooter', () => {
  const digest = '## Weekly Digest\n\n- PR #1';

  it('returns digest unchanged when disabled', () => {
    const config = { ...baseConfig, enabled: false, footerText: 'hello' };
    expect(appendFooter(digest, config)).toBe(digest);
  });

  it('returns digest unchanged when no footer content', () => {
    expect(appendFooter(digest, baseConfig)).toBe(digest);
  });

  it('appends footer with separator', () => {
    const config = { ...baseConfig, footerText: 'Powered by pr-digest' };
    const result = appendFooter(digest, config);
    expect(result).toContain('---');
    expect(result).toContain('Powered by pr-digest');
    expect(result.startsWith(digest)).toBe(true);
  });

  it('combines multiple footer elements', () => {
    const config = {
      ...baseConfig,
      footerText: 'Custom text',
      includeTimestamp: true,
      timestampFormat: 'iso' as const,
      includeRepoLink: true,
    };
    const context = {
      generatedAt: new Date('2024-06-01T00:00:00.000Z'),
      repoUrl: 'https://github.com/org/repo',
    };
    const result = appendFooter(digest, config, context);
    expect(result).toContain('Custom text');
    expect(result).toContain('2024-06-01T00:00:00.000Z');
    expect(result).toContain('https://github.com/org/repo');
  });
});
